// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCjOLf03nXf13qZttT-BDeXH7omuK9Vg8',
    appId: '1:751991579422:web:c1890d6eb4917eaebbdf0f',
    messagingSenderId: '751991579422',
    projectId: 'notes-app-d1436',
    authDomain: 'notes-app-d1436.firebaseapp.com',
    storageBucket: 'notes-app-d1436.firebasestorage.app',
    measurementId: 'G-0JE2HBW4YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWmDrQ2KBsVbFD3Fhc4yGWC5oVZG70Z0U',
    appId: '1:751991579422:android:5e0eef3ed642a304bbdf0f',
    messagingSenderId: '751991579422',
    projectId: 'notes-app-d1436',
    storageBucket: 'notes-app-d1436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBERDcRXsR0BNHy8KRPApoI6glTqMScL4Y',
    appId: '1:751991579422:ios:45947267602065e0bbdf0f',
    messagingSenderId: '751991579422',
    projectId: 'notes-app-d1436',
    storageBucket: 'notes-app-d1436.firebasestorage.app',
    iosBundleId: 'com.example.mobileNoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBERDcRXsR0BNHy8KRPApoI6glTqMScL4Y',
    appId: '1:751991579422:ios:45947267602065e0bbdf0f',
    messagingSenderId: '751991579422',
    projectId: 'notes-app-d1436',
    storageBucket: 'notes-app-d1436.firebasestorage.app',
    iosBundleId: 'com.example.mobileNoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCjOLf03nXf13qZttT-BDeXH7omuK9Vg8',
    appId: '1:751991579422:web:997cb3d0d3496e88bbdf0f',
    messagingSenderId: '751991579422',
    projectId: 'notes-app-d1436',
    authDomain: 'notes-app-d1436.firebaseapp.com',
    storageBucket: 'notes-app-d1436.firebasestorage.app',
    measurementId: 'G-L19MFXSXQW',
  );
}
